local is_development = true
local build_path = ""

function init(self)

	msg.post("@render:", "clear_color", {color = vmath.vector4(33 / 255, 33 / 255, 33 / 255, 0)})
	go.animate("/logo", "position.y", go.PLAYBACK_LOOP_PINGPONG, 255, go.EASING_INBACK, 0.96)

	--player.build_path( "D:/Defold/RAudioExtension/res/common/assets/")
	--player.build_path("/Users/lee/work/RAudioExtension/res/common/assets/")
	--player.build_path("/Users/kevinphillips/Work/defold/RAudioExtension/res/common/assets/")
		
	player.master_volume(1.0) -- works ok (0.0 .. 1.0)
	player.load_music("test_2.xm")
	player.play_music()	
	player.music_volume(1.0) -- works (0.0 .. 2.0 - depending on source file)
	player.music_pitch(1.0) -- works ok (0.0 .. 2.0)
	print("is Playing:", player.is_music_playing()) -- Check if music is playing
	print("Music length" , player.music_length())
	
end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end
