
local music = 0
local is_development = true
local build_path = ""

function init(self)

	player.build_path("/Users/lee/work/RAudioExtension/res/common/assets/")
	player.master_volume(1.0)
	player.load_music("test_1.xm")
	player.play_music()	
	player.music_volume(1.0)
	player.music_pitch(1.0)
	print("is Playing:", player.is_music_playing()) -- Check if music is playing
	print("Music length" , player.music_length())
	
end

function final(self)
	-- Add finalization code here
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Remove this function if not needed
end
